//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Bill_Management_Systm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int BILLID { get; set; }
        public string SHOPNAME { get; set; }
        public string ADDRESS { get; set; }
        public string DATE { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public string ITEM { get; set; }
    }
}
